version: '3'
services:
  db:
    container_name: laravel_db
    build: ./db/
    image: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: Password@1234
      MYSQL_DATABASE: laravel_db
    ports:
      - 3306:3306
  app:
    container_name: laravel_app
    build: ./app/
    image: laravel_app
    ports:
      - 80:8000
    links:
      - db
    volumes:
      - ../src:/var/www/html
      - ./app/init:/var/www/html/init
    stdin_open: true
    tty: true
    depends_on:
      - db